config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :promotions, only: %i[index show new create edit update destroy] do
    member do
      post 'generate_coupons'
      post 'approve'
    end
    get 'search', on: :collection
  end

  resources :product_categories, only: %i[index show new create edit update destroy] do
    get 'search', on: :collection
  end

  resources :coupons, only: %i[show] do
    post 'disable', on: :member
    post 'enable', on: :member
    get 'search', on: :collection
  end

  namespace :api, constraints: ->(req) { req.format == :json } do
    namespace :v1 do
      resources :coupons, only: %i[show], param: :code
      resources :product_categories, only: %i[show create update destroy], param: :code
        
    end
  end

end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
    has_and_belongs_to_many :promotions
    validates :name, :code, presence: true
    validates :name, :code, uniqueness: true
    SEARCHABLE_FIELDS = %w[name code].freeze

    def self.search(query)
        where(
            SEARCHABLE_FIELDS
                .map { |field| "#{field} LIKE :query" }
                .join(' OR '), 
             query: "%#{query}%")
        .limit(5)
    end
end

app/controllers/api/v1/product_categories_controller.rb
class Api::V1::ProductCategoriesController < Api::V1::ApiController
    before_action :set_product_category, only: %i[show update destroy]

    def show
    end

    def create
        @product_category = ProductCategory.create!(product_category_params)
        render :show
    end

    def update
        @product_category.update!(product_category_params)
        render :show
    end

    def destroy
        @product_category.destroy!
    end

    private

        def product_category_params
            params.require(:product_category).permit(:name, :code)
        end

        def set_product_category
            @product_category = ProductCategory.find_by!(code: params[:code])
        end

end

app/controllers/product_categories_controller.rb
class ProductCategoriesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_product_category, only: %i[show edit update destroy]

    def index
        @product_categories = ProductCategory.all
    end

    def show
    end

    def new
        @product_category = ProductCategory.new
    end

    def create
        @product_category = ProductCategory.new(product_category_params)
        if @product_category.save
            redirect_to @product_category
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @product_category.update(product_category_params)
            flash[:notice] = "#{t('activerecord.models.product_category.one')} editada com sucesso"
            redirect_to @product_category
        else
          render :edit
        end
    end

    def destroy
        if @product_category.destroy
            flash[:notice] = "#{t('activerecord.models.product_category.one')} deletada com sucesso"
            redirect_to @product_category
        end
    end

    def search
        @product_categories = ProductCategory.search(params[:q])
        render :index
    end

    private

        def product_category_params
            params.require(:product_category).permit(:name, :code)
        end

        def set_product_category
            @product_category = ProductCategory.find(params[:id])
        end
end

app/views/product_categories/_form.html.erb
<%= form_with model: product_category do |f| %>
    <% if product_category.errors.any?%>
        <h4>Não foi possível. Encontramos alguns erros:</h4>
        <ul>
            <% product_category.errors.full_messages.each do |message|%>
                <li><%= message %></li>
        </ul>
            <% end %>
    <% end %>

    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>
    <div>
        <%= f.label :code %>
        <%= f.text_field :code %>
    </div>
    <%= f.submit %>
    <% end%>

app/views/product_categories/edit.html.erb
<h1>Editar <%= t('activerecord.models.product_category.one') %></h1>

<%= render partial: "form", locals: { product_category: @product_category } %>

app/views/product_categories/index.html.erb
<%=form_with url: search_product_categories_path, method: :get do |f| %>
    <%= f.label :q, 'Busca' %>
    <%= f.text_field :q %>
    <%= f.submit 'Buscar', class: 'btn btn-primary' %>
<% end %>
<br />

<div>
<%= link_to 'Voltar', root_path, class: 'btn btn-secondary' %>
<%= link_to "Registrar #{t('activerecord.models.product_category.one')}", new_product_category_path, class: 'btn btn-success' %>
</div>

<% if @product_categories.empty? %>
    <h3>Nenhuma <%= t('activerecord.models.product_category.one') %> cadastrada</h3>
<% end%>

<% @product_categories.each do |product_category| %>
    <div class='card' style='width: 18rem;'>
        <div class='card-body'>
            <h3 class='card-title'><%= link_to product_category.name, product_category %></h3>
            <h4 class='card-subtitle'> <%= product_category.code %></h4>
            <%= link_to "Editar #{t('activerecord.models.product_category.one')}", 
                                    edit_product_category_path(product_category.id), class: 'btn btn-warning' %>
            <%= link_to "Deletar #{t('activerecord.models.product_category.one')}", 
                                    product_category_path(product_category.id), method: :delete, class: 'btn btn-danger' %>
        </div>
    </div>
<% end %>

app/views/product_categories/new.html.erb
<h1>Registrar <%= t('activerecord.models.product_category.one') %></h1>

<%= render partial: "form", locals: { product_category: @product_category } %>
    

app/views/product_categories/show.html.erb
<h3><%= @product_category.name %></h3>
<dl>
    <dt><%= ProductCategory.human_attribute_name(:name) %></dt>
    <dd><%= @product_category.name %></dd>
    <dt><%= ProductCategory.human_attribute_name(:code) %></dt>
    <dd><%= @product_category.code %></dd>
    <dt><%= ProductCategory.human_attribute_name(:promotions) %></dt>
    <% @product_category.promotions.each do |promotion| %>
        <dd><%= promotion.name %></dd>
    <% end%>
</dl>

<%= link_to 'Voltar', product_categories_path %>