config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :promotions, only: %i[index show new create edit update destroy] do
    member do
      post 'generate_coupons'
      post 'approve'
    end
    get 'search', on: :collection
  end

  resources :product_categories, only: %i[index show new create edit update destroy] do
    get 'search', on: :collection
  end

  resources :coupons, only: %i[show] do
    post 'disable', on: :member
    post 'enable', on: :member
    get 'search', on: :collection
  end

  namespace :api, constraints: ->(req) { req.format == :json } do
    namespace :v1 do
      resources :coupons, only: %i[show], param: :code
      resources :product_categories, only: %i[show create update destroy], param: :code
        
    end
  end

end

app/models/promotion.rb
class Promotion < ApplicationRecord
    belongs_to :user
    has_many :coupons, dependent: :delete_all
    has_and_belongs_to_many :product_categories
    has_one :promotion_approval
    has_one :approver, through: :promotion_approval, source: :user

    validates :name, :code, :discount_rate, :coupon_quantity, 
              :expiration_date, presence: true
    validates :name, :code, uniqueness: true
    SEARCHABLE_FIELDS = %w[name code description].freeze

    def generate_coupons!
        return if coupons?

        Coupon.transaction do
            (1..coupon_quantity).each do |number|
                coupons.create!(code: "#{code}-#{'%04d' % number}")
            end
        end
    end

    def coupons?
        coupons.any?
    end

    def self.search(query)
        where(
            SEARCHABLE_FIELDS
                .map { |field| "#{field} LIKE :query" }
                .join(' OR '), 
             query: "%#{query}%")
        .limit(5)
    end

    def approved?
        promotion_approval.present?
    end

    def can_approve?(current_user)
        user != current_user
    end
end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_promotion, only: %i[show edit update destroy generate_coupons approve]
    before_action :can_be_approved, only: %i[approve]

    def index
        @promotions = Promotion.all
    end

    def show
        
    end

    def new
        @promotion = Promotion.new
        @product_categories = ProductCategory.all
    end

    def create
        @promotion = current_user.promotions.new(promotion_params)
        if @promotion.save
            redirect_to @promotion
        else
            render :new
        end
    end

    def edit
        @product_categories = ProductCategory.all
    end

    def update
        if @promotion.update(promotion_params)
            redirect_to @promotion, notice: t('.success')
        else
          render :edit
        end
    end

    def destroy
        if @promotion.destroy
            redirect_to @promotion, notice: t('.success')
        end
    end

    def generate_coupons
        @promotion.generate_coupons!
        redirect_to @promotion, notice: t('.success')
    end

    def search
        @promotions = Promotion.search(params[:q])
        render :index
    end

    def approve
        current_user.promotion_approvals.create!(promotion: @promotion)
        PromotionMailer.with(promotion: @promotion, approver: current_user).approval_email.deliver_now
        byebug
        redirect_to @promotion, notice: "Promoção aprovada com sucesso"
    end
    
    private
        def set_promotion
            @promotion = Promotion.find(params[:id])
        end

        def promotion_params
            params
            .require(:promotion)
            .permit(:name, :expiration_date, :description,
                    :discount_rate, :code, :coupon_quantity, product_category_ids: [])
        end

        def can_be_approved
            redirect_to @promotion, alert: 'Ação não permitida' unless @promotion.can_approve?(current_user)
        end
    
end

app/views/promotions/_form.html.erb
<%= form_with model: promotion do |f| %>
    <% if promotion.errors.any?%>
        <h4>Não foi possível. Encontramos alguns erros:</h4>
        <ul>
            <% promotion.errors.full_messages.each do |message|%>
                <li><%= message %></li>
        </ul>
            <% end %>
    <% end %>

    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>
    <div>
        <%= f.label :description %>
        <%= f.text_area :description %>
    </div>
    <div>
        <%= f.label :code %>
        <%= f.text_field :code %>
    </div>
    <div>
        <%= f.label :discount_rate %>
        <%= f.number_field :discount_rate, in: 0..100, step: 0.1 %>
    </div>
    <div>
        <%= f.label :coupon_quantity %>
        <%= f.number_field :coupon_quantity, min: 1 %>
    </div>
    <div>
        <%= f.label :expiration_date %>
        <%= f.text_field :expiration_date %> <!--Changed to text_field instead date_field to avoid date format issues-->
    </div>
    <% if @product_categories %>
        <div>
            <%= f.label :product_categories %>
            <%= f.collection_check_boxes :product_category_ids, @product_categories, :id, :name %>
        </div>
    <% end %>
    <%= f.submit %>
    <% end%>

app/views/promotions/edit.html.erb
<h1>Editar <%= t("activerecord.models.promotion.one") %></h1>

<%= render partial: "form", locals: { promotion: @promotion } %>

app/views/promotions/index.html.erb
<%=form_with url: search_promotions_path, method: :get do |f| %>
    <%= f.label :q, 'Busca' %>
    <%= f.text_field :q %>
    <%= f.submit 'Buscar', class: 'btn btn-primary' %>
<% end %>

<br />

<%=form_with url: search_coupons_path, method: :get do |f| %>
    <%= f.label :code, 'Buscar cupom por código' %>
    <%= f.text_field :code %>
    <%= f.submit 'Buscar Cupom', class: 'btn btn-primary' %>
<% end %>

<br />

<%= link_to 'Voltar', root_path, class: 'btn btn-secondary' %>
<%= link_to "Registrar #{t("activerecord.models.promotion.one")}", new_promotion_path, class: 'btn btn-success' %>

<% if @promotions.empty? %>
    <h3>Nenhuma <%= t("activerecord.models.promotion.one") %> cadastrada</h3>
<% end%>

<% @promotions.each do |promotion| %>
    <div class='card' style='width: 18rem;'>
        <div class='card-body'>
            <h3 class='card-title'><%= link_to promotion.name, promotion %></h3>
            <dl>
                <dt><%= Promotion.human_attribute_name(:description) %></dt>
                <dd><%= promotion.description %></dd>
                <dt><%= Promotion.human_attribute_name(:discount_rate) %></dt>
                <dd><%= number_to_percentage promotion.discount_rate, precision: 2 %></dd>
            </dl>
                <%= link_to "Editar #{t("activerecord.models.promotion.one")}", edit_promotion_path(promotion.id), class: 'btn btn-warning' %>
                <%= link_to "Deletar #{t("activerecord.models.promotion.one")}", promotion_path(promotion.id), 
                                                                            data: {confirm: "Tem certeza? Essa operação não poderá ser desfeita."}, 
                                                                            method: :delete, class: 'btn btn-danger' %>
        </div>
    </div>
<% end %>

app/views/promotions/new.html.erb
<h1>Registrar uma promoção</h1>

<%= render partial: "form", locals: { promotion: @promotion } %>
    

app/views/promotions/show.html.erb
<h3><%= @promotion.name %></h3>
<dl>
    <dt><%= Promotion.human_attribute_name(:description) %></dt>
    <dd><%= @promotion.description %></dd>
    <dt><%= Promotion.human_attribute_name(:discount_rate) %></dt>
    <dd><%= number_to_percentage @promotion.discount_rate, precision: 2 %></dd>
    <dt><%= Promotion.human_attribute_name(:code) %></dt>
    <dd><%= @promotion.code %></dd>
    <dt><%= Promotion.human_attribute_name(:expiration_date) %></dt>
    <dd><%= @promotion.expiration_date.strftime '%d/%m/%Y' %></dd>
    <dt><%= Promotion.human_attribute_name(:coupon_quantity) %></dt>
    <dd><%= @promotion.coupon_quantity %></dd>
    <dt><%= Promotion.human_attribute_name(:product_categories) %></dt>
    <% @promotion.product_categories.each do |product_category| %>
        <dd><%= product_category.name %></dd>
    <% end%>
</dl>

<% if @promotion.approved? %>
    <p>Aprovada por: <%= @promotion.approver.email %></p>
    <% if @promotion.coupons.empty? %>
        <%= link_to "Gerar #{t('activerecord.models.coupon.other')}", generate_coupons_promotion_path(@promotion), method: :post %>
    <% end %>
<% elsif @promotion.can_approve?(current_user) %>
    <%= link_to 'Aprovar', approve_promotion_path(@promotion), data: {confirm: "Tem certeza? Essa operação não poderá ser desfeita."}, method: :post %>
<% end %>


<%= link_to 'Voltar', promotions_path %>


<% @promotion.coupons.each do |coupon|%>
    <div id="coupon-<%= coupon.code.parameterize %>">
        <p><%= coupon.code%> (<%= Coupon.human_attribute_name("status.#{coupon.status}")%>)</p>
        <% if coupon.active?%>
            <%= link_to 'Desabilitar', disable_coupon_path(coupon), method: :post %>
        <% else %>
            <%= link_to 'Habilitar', enable_coupon_path(coupon), method: :post %>
        <% end %>
    </div>
<% end %>